extends Node

signal resource_changed(resource_id: String, amount: int)
signal time_changed(day: int, hour: int, minute: int, second: int)
signal time_scale_changed(player_scale: float, effective_scale: float, numeric_multiplier: float, reason: String)
signal logical_time_tick(game_delta_seconds: float, numeric_multiplier: float)
signal gameplay_pause_changed(paused: bool)
signal game_over_changed(result: String, reason: String)
signal epilogue_changed(snapshot: Dictionary)
signal combat_enemy_presence_changed(active: bool, enemy_count: int, reason: String)
signal combat_wave_cleared(wave_number: int)
signal combat_audio_event(event: Dictionary)
signal day_started(day: int)
signal hour_started(day: int, hour: int)
signal building_clicked(building_id: String)
signal building_state_changed(building_id: String)
signal building_job_completed(building_id: String, job_type: String, result: Dictionary)
signal npc_building_entry_failed(npc_id: String, building_id: String, context: Dictionary)
signal crafting_state_changed(building_id: String)
signal horse_state_changed(horse_id: String)
signal horse_assignment_changed(horse_id: String, npc_id: String)
signal horse_birth_naming_requested(request: Dictionary)
signal horse_clicked(horse_id: String)
signal npc_clicked(npc_id: String)
signal enemy_clicked(enemy_id: String)
signal npc_dialogue_bubble_clicked(npc_id: String, dialogue_id: String)
signal npc_dialogue_emotion_presented(npc_id: String, presentation: Dictionary)
signal npc_state_changed(npc_id: String)
signal npc_level_up(npc_id: String, skill_points_gained: int)
signal npc_attribute_point_assigned(npc_id: String, attribute_name: String, result: Dictionary)
signal recruitment_changed(npc_id: String, recruited: bool)
signal npc_order_changed(npc_id: String, current_order: Dictionary)
signal npc_llm_activity_changed(npc_id: String, activity: Dictionary)
signal npc_plan_reevaluation_requested(npc_id: String, reason: String)
signal npc_daily_plan_changed(npc_id: String, plan: Array)
signal npc_proactive_talk_changed(npc_id: String, active: bool)
signal npc_hp_changed(npc_id: String, hp: int, max_hp: int)
signal world_feedback_requested(feedback: Dictionary)
signal npc_unconscious(npc_id: String)
signal npc_revived(npc_id: String)
signal npc_escape_started(npc_id: String, escape_result: Dictionary)
signal event_recorded(event: Dictionary)
signal npc_memory_changed(npc_id: String)
signal location_info_changed(location_id: String)
signal public_event_added(event: Dictionary)
signal notice_board_clicked
signal merchant_clicked
signal merchant_state_changed(active: bool, snapshot: Dictionary)
signal defense_device_deployed(deployment_id: String, snapshot: Dictionary)
signal defense_device_state_changed(snapshot: Dictionary)
signal defense_device_action_phase(deployment_id: String, phase_snapshot: Dictionary)
signal defense_device_action_resolved(deployment_id: String, action_result: Dictionary)
signal defense_device_clicked(deployment_id: String)
signal world_selection_cleared
signal piety_changed(current_piety: float, max_piety: float, delta: float, reason: String)
signal piety_ready(current_piety: float, max_piety: float, reason: String)
signal meteor_cast_started(cast_id: String, target_position: Vector3, radius: float)
signal meteor_impacted(cast_id: String, result: Dictionary)
